// ⚠️  Auto-generated by bini-router on every build — do not edit.
// Add routes by creating files in src/app/api/ only.
// Generated at: 2026-04-10T11:11:01.243Z

import { Hono } from 'https://deno.land/x/hono@v4.3.11/mod.ts';
import { cors } from 'https://deno.land/x/hono@v4.3.11/middleware.ts';
import _route0 from '../src/app/api/hello.ts';

const app = new Hono();
app.use('/api/*', cors({ origin: '*', allowMethods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS'], allowHeaders: ['Content-Type','Authorization'] }));
app.route('/api', _route0);

// Serve static files from dist (must come AFTER API routes)
app.get('/*', async (c) => {
  // Skip API routes - let them be handled first
  if (c.req.path.startsWith('/api/')) {
    return c.text('API route not found', 404);
  }
  
  const filePath = c.req.path === '/' ? '/index.html' : c.req.path;
  
  try {
    const file = await Deno.readFile(`./dist${filePath}`);
    const ext = filePath.split('.').pop();
    const contentType = 
      ext === 'html' ? 'text/html' :
      ext === 'css' ? 'text/css' :
      ext === 'js' ? 'application/javascript' :
      ext === 'json' ? 'application/json' :
      ext === 'png' ? 'image/png' :
      ext === 'jpg' || ext === 'jpeg' ? 'image/jpeg' :
      'text/plain';
    
    return new Response(file, {
      headers: { 'Content-Type': contentType }
    });
  } catch {
    // SPA fallback
    try {
      const indexHtml = await Deno.readFile('./dist/index.html');
      return new Response(indexHtml, {
        headers: { 'Content-Type': 'text/html' }
      });
    } catch {
      return c.text('File not found', 404);
    }
  }
});

Deno.serve({ port: Number(Deno.env.get('PORT') ?? 3000) }, app.fetch);
